easytrader/httrader.py
=> 华泰获取账户地方不对

easytrader/yjbtrader.py
=> fix(yjb): request mount bug

README.md
=> 添加关于银河证券的README的说明

easytrader/api.py, easytrader/config/xq.json, easytrader/xqtrader.py, xq.json
添加了一个利用雪球组合做虚拟盘的接口，操作和返回参数基本和佣金宝接口差不多，买卖委托单只能市价委托，调仓以调仓总金额(委托价格*委托数量)为准，支持未成交的委托撤单
=> 利用雪球组合做虚拟盘操作

easytrader/xqtrader.py
=> 持仓资金计算错误问题

easytrader/httrader.py
=> Update httrader.py - 当证券账户中有B股账户时，取股东账户时会出错。

easytrader/helpers.py, easytrader/httrader.py
1、增加可转债代码识别
2、修改ht账户上交所exchange_type设置
=> 增加可转债代码识别和ht的exchange_type设置

easytrader/config/yh.json, easytrader/yhtrader.py
=> Adding heartbeat and unlock

MANIFEST.in, easytrader/api.py, easytrader/config/yh.json, easytrader/webtrader.py, easytrader/yhtrader.py
Add MANIFEST.in so that python setup.py sdist can include README.md. And, add get_current_deal for " yh ", add support market price type for " yh ".
=> Adding get_current_deal and market price support for yh

easytrader/yhtrader.py
=> fix bug for yinhe: get position

easytrader/gftrader.py, easytrader/helpers.py
之前gftrader不兼容python2.7，所以修改了一下，项目很棒，我之前自己写了个，发现还是你写的好，大神啊~
=> make gftrader.py compatible with python2.7

easytrader/config/xq.json, easytrader/xqtrader.py
传过来的参数time_stamp是毫秒而不是秒，所以要除以1000. 另外加入例外处理，防止这些无关紧要的细节影响运行。
=> __time_strftime函数的bug

easytrader/xqtrader.py, xq.json
=> 修改雪球交易代码以支持美股、港股组合

easytrader/yhtrader.py
1.修正check_available_cancels遇到新股时候数据格式的bug。
2.增加了get_deal接口，可以获取历史成交明细，不设置参数则与get_current_deal返回相同，比get_current_deal多一些异常数据处理
=> 银河check_available_cancels, get_deal更新

README.md, easytrader/helpers.py
=> 增加查询今天可以申购的新股信息方法

easytrader/helpers.py
坑爹的雪球果然14号就不显示14号可以申购的新股了。调大size参数搞定。
=> 修复无法获取当日申购新股的bug

easytrader/config/gf.json, easytrader/gftrader.py
=> Patch 8 1.修改默认委托查询的参数，2.增加正常退出功能

README.md, easytrader/api.py, easytrader/follower.py, easytrader/joinquant_follower.py, easytrader/ricequant_follower.py, requirements.txt, setup.py
增加 Ricequant 模拟交易跟踪。
能够通过 run_id 跟踪 Ricequant 的模拟交易
=> 增加 Ricequant 模拟交易跟踪

easytrader/__init__.py, easytrader/gftrader.py, easytrader/webtrader.py, test_easytrader.py
=> bugfix:#176, Exception for "server force logged out" not correctly catched under gftrader

easytrader/__init__.py, easytrader/gftrader.py, easytrader/webtrader.py, test_easytrader.py
=> bugfix:#176, typo, Try to fix it again.

easytrader/yhtrader.py
处理有些非资金账户登录的情况，支持在配置文件中添加orgid和inputtype。
=> 处理有些非资金账户登录的情况，支持在配置文件中添加orgid和inputtype。

easytrader/xqtrader.py
1. 修正雪球获取委托单中状态和价格的错误;
2. 删除登陆不需要的 telephone 和 remember_me;
=> fix xqtrader

easytrader/grid_data_get_strategy.py
银河最新客户端保存xls文件后有较大几率出现文件不存在提示修改
=> add sleep wait file save success

easytrader/grid_data_get_strategy.py, easytrader/yh_clienttrader.py
=> 银河客户端修改登陆按钮为确定,更新验证码控件id,修复验证码截图范围过小导致只有三个数字被截取问题

easytrader/clienttrader.py
Signed-off-by: zhangyichent <zhangyi_0523@126.com>
=> missing window in _set_market_trade_type

easytrader/grid_strategies.py
1) sendkeys escape ~ in temp dir
=> bugfix for sendkeys

easytrader/yh_clienttrader.py
=> 银河客户端验证码去掉绘制边框

docs/help.md, docs/usage.md, easytrader/follower.py, easytrader/joinquant_follower.py
修改内容：
1）将原来在usage.md中的，有关问题解决的，移到了help.md中
2）重新编排了usage.md
3) fellower.py增加了re_search函数，以解决原来的re_find函数导致的“look-behind requires fixed-width pattern”错误。
4）joinquant_follower.py修改了函数：extract_strategy_id和 extract_strategy_name, 以能取到正确的id和name；修改了stock_shuffle_to_prefix函数中transaction["datetime"]在转换时的一个小错误。
修改效果：joinquant follow可用了。
=> 目的：让joinquant follow能运行起来。

easytrader/yh_clienttrader.py
可能是因为版本升级，目前Binarystar.exe看起来有些问题，但是直接使用xiadan.exe可以，不过xiadan.exe的登陆界面可能已经更新，造成无法自动登陆，因此更新了相关的“登陆”按钮查找方式。
=> 修正银河下单程序登陆

easytrader/grid_strategies.py
之前的代码没有考虑到识别出空格和换行符的情况，因此很多识别正确的结果也被当做错误忽略掉了。
修改后经本地测试，现在获取持仓信息基本不会错误超过5次，极快地提升了获取速度。
=> optimization: 优化验证码识别结果，加快持仓获取速度
